sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t arminsarabi/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true stephengrider/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'eu-central-1'
  app: 'docker-react'
  env: 'Dockerreact-env'
  bucket_name: 'eelasticbeanstalk-eu-central-1-811869624025'
  bucket_path: 'docker-react'
  on:
    branch: main
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: "$AWS_SECRET_KEY"